export { ErrorPage } from "./error/errorPage";
export { MainPage } from "./main/mainPage";
export { RegisterPage } from "./login/registerPage";
export { LoginPage } from "./login/loginPage";
export { AccountPage } from "./accountPage/accountPage";
// export { EditProfilePage } from "./editProfilePage/editProfilePage";
export { ProfilesPage } from "./profilesPage/profilesPage";
export { ProfilePage } from "./profilePage/profilePage";
export { CreateTaskPage } from "./createTaskPage/createTaskPage";
export { EditTaskPage } from "./editTaskPage/editTaskPage";
export { TasksPage } from "./tasksPage/tasksPage";
export { TaskPage } from "./taskPage/taskPage";
